services:
    bot:
        container_name: research-bot-bot
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
        env_file:
            - path: ./.env
              required: false
            - path: ./.env.production
              required: false
volumes:

    
networks:
    default: {}